set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVCMOS33} [get_ports a]
set_property -dict {PACKAGE_PIN N8 IOSTANDARD LVCMOS33} [get_ports b]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD LVCMOS33} [get_ports c]

set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports {o[7]}]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports {o[6]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports {o[5]}]
set_property -dict {PACKAGE_PIN N7 IOSTANDARD LVCMOS33} [get_ports {o[4]}]
set_property -dict {PACKAGE_PIN M7 IOSTANDARD LVCMOS33} [get_ports {o[3]}]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD LVCMOS33} [get_ports {o[2]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports {o[1]}]
set_property -dict {PACKAGE_PIN N5 IOSTANDARD LVCMOS33} [get_ports {o[0]}]